[mypy]
strict = True
warn_unused_ignores = True
no_implicit_optional = True
check_untyped_defs = True
disallow_untyped_defs = True
mypy_path = typestubs

[mypy-aiosqlite]
ignore_missing_imports = True

[mypy-aiosqlite.*]
ignore_missing_imports = True

[mypy-opentelemetry]
ignore_missing_imports = True

[mypy-opentelemetry.*]
ignore_missing_imports = True

[mypy-tenacity]
ignore_missing_imports = True

[mypy-tenacity.*]
ignore_missing_imports = True

[mypy-prometheus_client]
ignore_missing_imports = True

[mypy-prometheus_client.*]
ignore_missing_imports = True
