services:
  sentinelflow:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "9108:9108"
      - "9109:9109"
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
